services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=patient-reports'
      - 'POSTGRES_PASSWORD=reports'
      - 'POSTGRES_USER=reports'
    ports:
      - '5432:5432'
